// Diet choices backed by catalog data. Allergen flags (gluten, nuts, dairy) stay
// out until reviewed per-ingredient tags exist (P0-06, ADD-03).
export const DIET_FILTERS = ["vegan", "vegetarian"];

export const DEFAULT_PROFILE = {
  name: "",
  budget: "save",
  dietaryNeeds: [],
  foodSources: ["packed", "cafeteria", "home"],
  familyPrep: true,
};

export const FOOD_IDEAS = [
  {
    id: "banana-pretzels",
    name: "Banana + pretzels",
    moments: ["quick", "pre", "regular"],
    sources: ["packed", "cafeteria", "store", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "Simple, portable carbs with no prep.",
  },
  {
    id: "applesauce-rice-cakes",
    name: "Applesauce pouch + rice cakes",
    moments: ["quick", "pre"],
    sources: ["packed", "store", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
    note: "Easy to pack and usually gentle before activity.",
  },
  {
    id: "fig-bar-fruit",
    name: "Fig bar + fresh fruit",
    moments: ["quick", "pre", "regular"],
    sources: ["packed", "cafeteria", "store", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A shelf-stable option for a bag or locker.",
  },
  {
    id: "cereal-milk",
    name: "Cereal cup + shelf-stable soy milk",
    moments: ["quick", "pre", "regular", "recovery"],
    sources: ["packed", "store", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "Easy carbs plus protein without needing a refrigerator.",
  },
  {
    id: "bagel-jam",
    name: "Bagel or toast + jam",
    moments: ["pre", "regular", "recovery"],
    sources: ["packed", "cafeteria", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A familiar option when you have a little time.",
  },
  {
    id: "sunbutter-sandwich",
    name: "Sunflower-butter banana sandwich",
    moments: ["pre", "regular", "recovery"],
    sources: ["packed", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "Packable fuel with carbs plus staying power.",
  },
  {
    id: "oatmeal-fruit",
    name: "Oatmeal + fruit",
    moments: ["regular", "pre", "recovery"],
    sources: ["cafeteria", "home"],
    cost: "save",
    portable: false,
    needsHeat: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A lower-cost warm option that can work before or after activity.",
  },
  {
    id: "hummus-pita",
    name: "Hummus + pita + grapes",
    moments: ["regular", "recovery"],
    sources: ["packed", "store", "home"],
    cost: "save",
    portable: true,
    needsCold: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A packable mix of carbs and protein when kept cold.",
  },
  {
    id: "turkey-sandwich",
    name: "Turkey sandwich + fruit",
    moments: ["regular", "recovery"],
    sources: ["packed", "cafeteria", "store", "home"],
    cost: "standard",
    portable: true,
    needsCold: true,
    vegan: false,
    vegetarian: false,
    dairyFree: true,
    glutenFree: false,
    note: "A familiar full snack or meal for a busy handoff.",
  },
  {
    id: "tuna-crackers",
    name: "Tuna pouch + crackers + fruit cup",
    moments: ["regular", "recovery"],
    sources: ["packed", "store", "home"],
    cost: "standard",
    portable: true,
    vegan: false,
    vegetarian: false,
    dairyFree: true,
    glutenFree: false,
    note: "Shelf-stable protein and carbs for an away day.",
  },
  {
    id: "yogurt-cereal",
    name: "Yogurt + fruit + cereal",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "home", "store"],
    cost: "standard",
    portable: false,
    needsCold: true,
    vegan: false,
    vegetarian: true,
    dairyFree: false,
    glutenFree: false,
    note: "A quick carb-and-protein recovery option when kept cold.",
  },
  {
    id: "soy-yogurt",
    name: "Soy yogurt + berries + granola",
    moments: ["regular", "recovery"],
    sources: ["packed", "store", "home"],
    cost: "standard",
    portable: true,
    needsCold: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A dairy-free recovery option that packs well with an ice pack.",
  },
  {
    id: "bean-rice-bowl",
    name: "Bean-and-rice bowl + fruit",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "home"],
    cost: "save",
    portable: false,
    needsHeat: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
    note: "Budget-friendly and balanced for a full meal window.",
  },
  {
    id: "chicken-tofu-bowl",
    name: "Chicken rice bowl",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "home"],
    cost: "standard",
    portable: false,
    needsHeat: true,
    vegan: false,
    vegetarian: false,
    dairyFree: true,
    glutenFree: true,
    note: "A practical meal with carbs and protein after training.",
  },
  {
    id: "bean-burrito",
    name: "Bean burrito + salsa",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "packed", "home"],
    cost: "save",
    portable: true,
    needsHeat: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A low-cost meal that can be packed and reheated.",
  },
  {
    id: "pasta-salad",
    name: "Pasta salad + chickpeas",
    moments: ["regular", "recovery"],
    sources: ["packed", "home"],
    cost: "save",
    portable: true,
    needsCold: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "Make-ahead carbs and protein for school-to-sport days.",
  },
  {
    id: "eggs-toast",
    name: "Eggs + toast + fruit",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "home"],
    cost: "save",
    portable: false,
    needsHeat: true,
    vegan: false,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A familiar recovery meal using basic ingredients.",
  },
  {
    id: "edamame-rice",
    name: "Edamame + rice + fruit",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "home"],
    cost: "save",
    portable: false,
    needsHeat: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
    note: "A plant-based meal with carbs and protein.",
  },
  {
    id: "milk-banana",
    name: "Chocolate milk + banana",
    moments: ["recovery"],
    sources: ["cafeteria", "store", "home"],
    cost: "standard",
    portable: false,
    needsCold: true,
    vegan: false,
    vegetarian: true,
    dairyFree: false,
    glutenFree: true,
    note: "Fast recovery fuel when a full meal is still a while away.",
  },
  {
    id: "fruit-crackers-cheese",
    name: "Fruit cup + crackers + cheese",
    moments: ["regular", "recovery"],
    sources: ["cafeteria", "packed", "store"],
    cost: "standard",
    portable: true,
    needsCold: true,
    vegan: false,
    vegetarian: true,
    dairyFree: false,
    glutenFree: false,
    note: "Easy to find at school or pack from home.",
  },
  {
    id: "seed-trail-mix",
    name: "Seed mix + dried fruit",
    moments: ["quick", "regular", "during"],
    sources: ["packed", "store", "home"],
    cost: "standard",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
    note: "Compact, shelf-stable fuel for longer days.",
  },
  {
    id: "smoothie-toast",
    name: "Fruit smoothie + toast",
    moments: ["pre", "regular", "recovery"],
    sources: ["cafeteria", "store", "home"],
    cost: "standard",
    portable: false,
    needsCold: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "A drinkable option when solid food is less appealing.",
  },
  {
    id: "sports-drink-crackers",
    name: "Familiar sports drink + crackers",
    moments: ["during", "quick"],
    sources: ["packed", "store", "cafeteria"],
    cost: "standard",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
    note: "Most useful during longer or harder sessions; water is fine for many shorter ones.",
  },
  {
    id: "juice-applesauce",
    name: "Juice box + applesauce pouch",
    moments: ["quick", "during"],
    sources: ["packed", "cafeteria", "store", "home"],
    cost: "save",
    portable: true,
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
    note: "A simple, easy-to-carry carb option when time is tight.",
  },
];

export const MEAL_INGREDIENTS = {
  "banana-pretzels": [
    ["Bananas", "bananas"],
    ["Pretzels", "pretzels"],
  ],
  "applesauce-rice-cakes": [
    ["Applesauce pouches", "applesauce"],
    ["Rice cakes", "rice-cakes"],
  ],
  "fig-bar-fruit": [
    ["Fig bars", "fig-bars"],
    ["Fresh fruit", "bananas"],
  ],
  "cereal-milk": [
    ["Cereal", "cereal"],
    ["Shelf-stable soy milk", "soy-milk"],
  ],
  "bagel-jam": [
    ["Bagels or bread", "bread"],
    ["Jam", "jam"],
  ],
  "sunbutter-sandwich": [
    ["Whole-grain bread", "bread"],
    ["Sunflower-seed butter", "sunbutter"],
    ["Bananas", "bananas"],
  ],
  "oatmeal-fruit": [
    ["Oats", "oats"],
    ["Fresh or frozen fruit", "frozen-berries"],
  ],
  "hummus-pita": [
    ["Hummus", "hummus"],
    ["Pita", "pita"],
    ["Grapes", "grapes"],
  ],
  "turkey-sandwich": [
    ["Whole-grain bread", "bread"],
    ["Turkey", "turkey"],
    ["Fresh fruit", "apples"],
  ],
  "tuna-crackers": [
    ["Tuna pouches", "tuna-pouches"],
    ["Crackers", "crackers"],
    ["Fruit cups", "fruit-cups"],
  ],
  "yogurt-cereal": [
    ["Yogurt", "yogurt"],
    ["Fresh fruit", "bananas"],
    ["Cereal", "cereal"],
  ],
  "soy-yogurt": [
    ["Soy yogurt", "soy-yogurt"],
    ["Frozen berries", "frozen-berries"],
    ["Granola", "granola"],
  ],
  "bean-rice-bowl": [
    ["Canned beans", "beans"],
    ["Rice", "rice"],
    ["Fresh fruit", "apples"],
  ],
  "chicken-tofu-bowl": [
    ["Chicken", "chicken"],
    ["Rice", "rice"],
    ["Vegetables", "baby-carrots"],
  ],
  "bean-burrito": [
    ["Canned beans", "beans"],
    ["Tortillas", "tortillas"],
    ["Salsa", "salsa"],
  ],
  "pasta-salad": [
    ["Pasta", "pasta"],
    ["Chickpeas", "chickpeas"],
    ["Vegetables", "baby-carrots"],
  ],
  "eggs-toast": [
    ["Eggs", "eggs"],
    ["Whole-grain bread", "bread"],
    ["Fresh fruit", "bananas"],
  ],
  "edamame-rice": [
    ["Edamame", "edamame"],
    ["Rice", "rice"],
    ["Fresh fruit", "apples"],
  ],
  "milk-banana": [
    ["Chocolate milk", "chocolate-milk"],
    ["Bananas", "bananas"],
  ],
  "fruit-crackers-cheese": [
    ["Fruit cups", "fruit-cups"],
    ["Crackers", "crackers"],
    ["Cheese sticks", "cheese-sticks"],
  ],
  "seed-trail-mix": [
    ["Seed mix", "seed-mix"],
    ["Dried fruit", "dried-fruit"],
  ],
  "smoothie-toast": [
    ["Fresh or frozen fruit", "frozen-berries"],
    ["Whole-grain bread", "bread"],
  ],
  "sports-drink-crackers": [
    ["Sports drink", "sports-drink"],
    ["Crackers", "crackers"],
  ],
  "juice-applesauce": [
    ["Juice boxes", "juice"],
    ["Applesauce pouches", "applesauce"],
  ],
};

const chicken = FOOD_IDEAS.find((i) => i.id === "chicken-tofu-bowl");
FOOD_IDEAS.push({
  ...chicken,
  id: "tofu-bowl",
  name: "Tofu rice bowl",
  vegan: true,
  vegetarian: true,
  cost: "save",
});
MEAL_INGREDIENTS["tofu-bowl"] = [
  ["Tofu", "tofu"],
  ["Rice", "rice"],
  ["Vegetables", "baby-carrots"],
];
const milk = FOOD_IDEAS.find((i) => i.id === "milk-banana");
FOOD_IDEAS.push({
  ...milk,
  id: "soy-milk-banana",
  name: "Soy milk + banana",
  vegan: true,
  dairyFree: true,
  cost: "save",
});
MEAL_INGREDIENTS["soy-milk-banana"] = [
  ["Soy milk", "soy-milk"],
  ["Bananas", "bananas"],
];
const exampleAmounts = {
  bananas: [1, "piece"],
  apples: [1, "piece"],
  bread: [2, "piece"],
  pretzels: [30, "g"],
  sunbutter: [30, "g"],
  "soy-milk": [250, "ml"],
  "chocolate-milk": [250, "ml"],
  rice: [1, "portion"],
  oats: [40, "g"],
  cereal: [30, "g"],
  "rice-cakes": [2, "piece"],
  jam: [20, "g"],
  eggs: [2, "piece"],
};
// Household example amounts for every idea ingredient (IDEA-07). These are
// examples, not targets; the Ideas page says so next to the list.
const displayAmounts = {
  bananas: "1 banana",
  bread: "2 slices of bread",
  pretzels: "1 small bag of pretzels",
  "rice-cakes": "2 rice cakes",
  eggs: "2 eggs",
  applesauce: "1 applesauce pouch",
  "fig-bars": "2 fig bars",
  cereal: "1 cup of cereal",
  "soy-milk": "1 cup of soy milk",
  jam: "1 spoonful of jam",
  sunbutter: "2 tablespoons of sunflower-seed butter",
  oats: "1 bowl of oatmeal",
  "frozen-berries": "1 cup of fruit",
  hummus: "1 small cup of hummus",
  pita: "1 pita",
  grapes: "1 handful of grapes",
  turkey: "A few slices of turkey",
  apples: "1 apple or other fruit",
  "tuna-pouches": "1 tuna pouch",
  crackers: "1 handful of crackers",
  "fruit-cups": "1 fruit cup",
  yogurt: "1 yogurt cup",
  "soy-yogurt": "1 soy yogurt cup",
  granola: "1 handful of granola",
  beans: "1 scoop of beans",
  rice: "1 scoop of rice",
  chicken: "A few strips of chicken",
  "baby-carrots": "1 handful of vegetables",
  tortillas: "2 tortillas",
  salsa: "1 spoonful of salsa",
  pasta: "1 bowl of pasta",
  chickpeas: "1 scoop of chickpeas",
  edamame: "1 cup of edamame",
  "chocolate-milk": "1 carton of chocolate milk",
  "cheese-sticks": "1 cheese stick",
  "seed-mix": "1 small handful of seed mix",
  "dried-fruit": "1 small box of dried fruit",
  "sports-drink": "1 bottle of sports drink",
  juice: "1 juice box",
  tofu: "1 scoop of tofu",
};
for (const key of Object.keys(MEAL_INGREDIENTS))
  MEAL_INGREDIENTS[key] = MEAL_INGREDIENTS[key].map(([name, id]) => [
    name,
    id,
    ...(exampleAmounts[id] || [1, "portion"]),
    displayAmounts[id] ||
      (exampleAmounts[id] &&
      !["piece", "portion"].includes(exampleAmounts[id][1])
        ? `${exampleAmounts[id][0]} ${exampleAmounts[id][1]} ${name.toLowerCase()}`
        : `${name}, to suit your appetite`),
  ]);

export const GROCERY_GOALS = [
  {
    id: "school-week",
    label: "School + practice week",
    description: "Packable snacks, quick breakfasts, and easy dinners.",
  },
  {
    id: "practice-fuel",
    label: "Practice fuel",
    description: "Simple food before activity plus recovery basics.",
  },
  {
    id: "away-game",
    label: "Away game",
    description: "Portable, shelf-stable food for travel and long days.",
  },
  {
    id: "recovery-meals",
    label: "Recovery meals",
    description: "Carbs, protein, produce, and easy meal building.",
  },
  {
    id: "restock-basics",
    label: "Restock basics",
    description: "Affordable staples that work across the week.",
  },
];

export const GROCERY_CATALOG = [
  {
    id: "bananas",
    name: "Bananas",
    category: "Produce",
    price: 2.25,
    goals: [
      "school-week",
      "practice-fuel",
      "away-game",
      "recovery-meals",
      "restock-basics",
    ],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "apples",
    name: "Apples",
    category: "Produce",
    price: 4.5,
    goals: ["school-week", "away-game", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "frozen-berries",
    name: "Frozen berries",
    category: "Produce",
    price: 4.25,
    goals: ["school-week", "recovery-meals"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "baby-carrots",
    name: "Baby carrots",
    category: "Produce",
    price: 2.5,
    goals: ["school-week", "away-game", "recovery-meals"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "bread",
    name: "Whole-grain bread",
    category: "Grains",
    price: 3.5,
    goals: ["school-week", "practice-fuel", "recovery-meals", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
  },
  {
    id: "tortillas",
    name: "Tortillas",
    category: "Grains",
    price: 3.25,
    goals: ["school-week", "away-game", "recovery-meals", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
  },
  {
    id: "oats",
    name: "Oats",
    category: "Grains",
    price: 4,
    goals: ["school-week", "practice-fuel", "recovery-meals", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
  },
  {
    id: "rice",
    name: "Rice",
    category: "Grains",
    price: 4.5,
    goals: ["school-week", "recovery-meals", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "pretzels",
    name: "Pretzels",
    category: "Packable",
    price: 3.25,
    goals: ["school-week", "practice-fuel", "away-game", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
  },
  {
    id: "applesauce",
    name: "Applesauce pouches",
    category: "Packable",
    price: 4.75,
    goals: ["school-week", "practice-fuel", "away-game"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "fig-bars",
    name: "Fig bars",
    category: "Packable",
    price: 5,
    goals: ["school-week", "practice-fuel", "away-game"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
  },
  {
    id: "crackers",
    name: "Crackers",
    category: "Packable",
    price: 3.5,
    goals: ["school-week", "practice-fuel", "away-game", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: false,
  },
  {
    id: "beans",
    name: "Canned beans",
    category: "Protein",
    price: 2.5,
    goals: ["school-week", "recovery-meals", "restock-basics"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "Protein",
    price: 4,
    goals: ["school-week", "recovery-meals", "restock-basics"],
    vegan: false,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "chicken",
    name: "Chicken",
    category: "Protein",
    price: 9,
    goals: ["school-week", "recovery-meals"],
    vegan: false,
    vegetarian: false,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "tofu",
    name: "Tofu",
    category: "Protein",
    price: 3.5,
    goals: ["school-week", "recovery-meals"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "tuna-pouches",
    name: "Tuna pouches",
    category: "Protein",
    price: 5.5,
    goals: ["away-game", "recovery-meals"],
    vegan: false,
    vegetarian: false,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "sunbutter",
    name: "Sunflower-seed butter",
    category: "Protein",
    price: 6.5,
    goals: ["school-week", "practice-fuel", "away-game"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "yogurt",
    name: "Yogurt",
    category: "Cold",
    price: 5,
    goals: ["school-week", "practice-fuel", "recovery-meals"],
    vegan: false,
    vegetarian: true,
    dairyFree: false,
    glutenFree: true,
  },
  {
    id: "soy-milk",
    name: "Shelf-stable soy milk",
    category: "Drinks",
    price: 4.5,
    goals: ["school-week", "practice-fuel", "away-game", "recovery-meals"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "sports-drink",
    name: "Sports drink",
    category: "Drinks",
    price: 6,
    goals: ["practice-fuel", "away-game"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
  {
    id: "cheese-sticks",
    name: "Cheese sticks",
    category: "Cold",
    price: 5,
    goals: ["school-week", "away-game", "recovery-meals"],
    vegan: false,
    vegetarian: true,
    dairyFree: false,
    glutenFree: true,
  },
  {
    id: "hummus",
    name: "Hummus",
    category: "Cold",
    price: 4,
    goals: ["school-week", "away-game", "recovery-meals"],
    vegan: true,
    vegetarian: true,
    dairyFree: true,
    glutenFree: true,
  },
];
